spring.application.name=projekt_logowanie

# Nowa konfiguracja - Profesjonalna baza PostgreSQL w Dockerze
spring.datasource.url=jdbc:postgresql://localhost:5432/cyber_db
spring.datasource.username=admin
spring.datasource.password=admindb
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver

# Ustawienia Hibernate dla PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Opcjonalnie: Jeśli chce Pan widzieć czytelne zapytania SQL w konsoli
spring.jpa.properties.hibernate.format_sql=true